### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by XTL-HAO** [lissettecarlr/speaker-diarization#1]
Traceback (most recent call last):
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001FA20454DD0>: Failed to establish a ne
w connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url:
/TRvlvr/application_data/main/vr_model_data/model_data_new.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection
 object at 0x000001FA20454DD0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GELIDAI\speaker-diarization-master\client.py", line 160, in <module>
    client = sd_user_client()
             ^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\speaker-diarization-master\client.py", line 32, in __init__
    self.separator.load_model(model_filename = os.getenv("uvr5_model_filename"))
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\audio_separator\separator\separator.py", line 642, in load_model
    model_data = self.load_model_data_using_hash(model_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\audio_separator\separator\separator.py", line 525, in load_model_data_using_hash
    self.download_file_if_not_exists(vr_model_data_url, vr_model_data_path)
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\audio_separator\separator\separator.py", line 300, in download_file_if_not_exists
    response = requests.get(url, stream=True, timeout=300)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GELIDAI\Anacoda3\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with ur
l: /TRvlvr/application_data/main/vr_model_data/model_data_new.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnect
ion object at 0x000001FA20454DD0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by lissettecarlr** [comment]
You can try using a proxy to make the request。

**Comment by XTL-HAO** [comment]
ok
